version: '3.8'

services:
  app:
    image: mo3az014/gym-manager-central:latest
    container_name: gym-manager-central-app
    platform: linux/amd64
    ports:
      - "80:80"
    environment:
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - SERVER_NAME=${SERVER_NAME}
    depends_on:
      - mysql-db
    networks:
      - laravel
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: gym-manager-central-mysql-db
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=32M --innodb-log-file-size=16M --max-connections=50
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gym-manager-central-phpmyadmin
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql-db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel: